### ISSUE TITLE
Include custom rules in extension

### ISSUE THREAD

**Issue by mschoettle** [DavidAnson/vscode-markdownlint#336]
I am trying to use `markdownlint` (and `markdownlint-cli2`) for a project and would like to have a setup where the vscode extension, pre-commit and `markdownlint-cli2` provide consistent results. This works generally fine. However, I would like to include a custom rule.

`.markdownlint-cli2.yaml`:

```yaml
customRules:
  # Enforce one sentence per line
  # See: https://github.com/DavidAnson/markdownlint/pull/719
  - "markdownlint-rule-max-one-sentence-per-line"
```

`.pre-commit.config.yaml` (excerpt):

```yaml
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2-rules-docker
```

I added the following lines to `.vscode/settings.json`: 

```json
"markdownlint.customRules": [
      "{aepfli.markdownlint-rule-max-one-sentence-per-line}/npm/rule/package",
    ]
```

My initial assumption was that vscode/the extension would then install this package. However, based on what I understand after some investigation this is not the case.

Since there is a supplementary Docker image that includes custom rules I wonder if it would be possible to include the same custom rules in the vscode extension?
