### ISSUE TITLE
Using parameters "siblings_only" and "allow_different_nesting" for Rule MD024

### ISSUE THREAD

**Issue by RikeKroeger** [DavidAnson/vscode-markdownlint#44]
The parameters "siblings_only" and "allow_different_nesting" for Rule MD024 do not seem to work.  I am using a .markdownlint.yaml in my working directory for the configuration:
```
default: true
MD024:
    siblings_only: true
    allow_different_nesting: true
```
The parameters are relatively new to the markdownlint project (https://github.com/DavidAnson/markdownlint). Did I make a mistake or is there any chance they haven't been included in the vscode-markdownlint yet, but will be soon? Any help is highly appreciated!
