### ISSUE TITLE
Lint all files in a workspace

### ISSUE THREAD

**Issue by borekb** [DavidAnson/vscode-markdownlint#47]
Currently, only the opened files are linted. It would be useful to have a command to lint all Markdown files in a workspace.

**Comment by DavidAnson** [comment]
The way VS Code works, I’m not sure you can report violations against documents that are not open. But I can look into this, thanks!

**Comment by DavidAnson** [comment]
I don't see a good way to implement this as a VS Code extension with the way things are today. There are two main issues:

1. There's currently no good support for listing all files in a workspace *with* the configured exclusions (ex: `node_modules`) applied so unrelated files are ignored. This issue has more detail: https://github.com/Microsoft/vscode/issues/48674
2. The process of linting and reporting errors is based on the `TextDocument` interface and the way to get an instance of that is to open the file in the VS Code editor. But we don't want to open (then close?) every Markdown file in a workspace when this command is run because that's very intrusive (and probably slow).

If/when good solutions to the above show up, I'll revisit this issue.

**Comment by lxp** [comment]
Would it be possible to lint all files for checking if they have any linting error and then only open those files in the VS Code editor that have linting errors?

**Comment by DavidAnson** [comment]
Yes, but per item 1 above, there is no easy way to know what the project exclusions are. Linting, for example, `node_modules` would create so much noise that nobody would ever use this feature.

Re-implementing (and maintaining) the logic VS Code uses for this is not something I’d like to sign up for.

**Comment by Kissaki** [comment]
Related/Similar ESLint ticket for linting all files rather than just open ones, which has some discussion and links that may be helpful https://github.com/Microsoft/vscode-eslint/issues/91. It is still unresolved as well.

**Comment by koppor** [comment]
My workaround is to use the [GitHub markdown-linting-action](https://github.com/marketplace/actions/markdown-linting-action) for it:
 
```yaml
name: Tests
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Lint all files
        uses: avto-dev/markdown-lint@v1
        with:
          args: 'en/'
          config: '.markdownlint.yml'
```

The `.markdownlint.yml` is a config as outlined at https://github.com/DavidAnson/vscode-markdownlint#configure. In case the default rules are good enough, one can just omit the file. However, it may make sense to disable the line-length-check (MD013)
